beehive/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from register import urls as register_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Give the register app the main namespace. This is where I want most
    # of the nice URLs.
    url(r'', include(register_urls, namespace='register'))
]

register/urls.py
from django.conf.urls import url

from register import views

urlpatterns = [
    url(
        r'^torrents/',
        views.TorrentList.as_view(),
        name='torrent-list'
    ),
    url(
        r'^torrent/(?P<slug>[0-9a-f]+)',
        views.TorrentDetail.as_view(),
        name='torrent-detail'
    ),
]

register/models.py
import binascii

from django.core.urlresolvers import reverse
from django.db import models

import utils


class Torrent(models.Model):
    name = models.CharField(
        max_length=256,
        help_text="The torrent's 'name'. Torrents don't really have names, "
                  "so it's just the original file name."
    )

    date_created = models.DateTimeField(
        blank=True,
        null=True,
        help_text="The metainfo-reported torrent creation date."
    )

    created_by = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        help_text="The metainfo-reported creator (program) of the torrent."
    )

    comment = models.TextField(
        blank=True,
        null=True,
        help_text="The metainfo-reported comment."
    )

    piece_length = models.PositiveSmallIntegerField(
        help_text='The length (in bytes) of each torrent piece.'
    )

    pieces_hash = models.BinaryField(
        help_text='The concatenation of all piece hash values.'
    )

    private = models.BooleanField(
        help_text='Is this torrent private? As per BEP-27.'
    )

    raw_metainfo = models.BinaryField(
        help_text="The raw un-edited torrent metainfo file."
    )

    info_hash = models.BinaryField(
        blank=True,
        unique=True,
        help_text='The SHA1 hash of the info dict from the metainfo file.'
    )

    info_hash_hex = models.CharField(
        blank=True,
        max_length=100,
        unique=True,
        help_text='The hex-encoded info hash.'
    )

    @property
    def hexcode(self):
        return self.info_hash_hex[0:6]

    def clean(self):
        self.info_hash = utils.calculate_info_hash(str(self.raw_metainfo))
        self.info_hash_hex = binascii.hexlify(self.info_hash)

    def get_absolute_url(self):
        return reverse('register:torrent-detail', args=[self.info_hash_hex])


class File(models.Model):
    name = models.CharField(
        max_length=256,
        help_text='The name of the file, including the path.'
    )

    length = models.PositiveSmallIntegerField(
        help_text="The file's length, in bytes."
    )

    file_hash = models.CharField(
        blank=True,
        null=True,
        max_length=32,
        help_text="The file's MD5 hash (hex. encoded). Blank for directories."
    )

    torrent = models.ForeignKey(
        'register.Torrent'
    )

    @property
    def owning_directory(self):
        # wicked bad code!
        return '/'.join(self.name.split('/')[1:-1])

    @property
    def filename(self):
        return self.name.split('/')[-1]

tracker/models.py
from django.db import models

# Create your models here.

register/views.py
from django.views import generic

import models


class TorrentDetail(generic.DetailView):
    model = models.Torrent
    slug_field = 'info_hash_hex'


class TorrentList(generic.ListView):
    model = models.Torrent

tracker/views.py
from django.shortcuts import render

# Create your views here.

register/templates/register/torrent_detail.html
{% extends 'base.html' %}

{% block heading %}
    {{ object.name }}

    {% if object.date_created %}
        <small>{{ object.date_created }}</small>
    {% endif %}
{% endblock %}

{% block content %}
    <h3>General Information</h3>
    <table class="table table-condensed">
        <tr>
            <td class="col-sm-2 col-lg-1"><strong>Name</strong></td>
            <td>{{ object.name }}</td>
        </tr>
        {% if object.date_created %}
            <tr>
                <td><strong>Created on</strong></td>
                <td>{{ object.date_created }}</td>
            </tr>
        {% endif %}
        {% if object.created_by %}
            <tr>
                <td><strong>Created by</strong></td>
                <td>{{ object.created_by }}</td>
            </tr>
        {% endif %}
        <tr>
            <td><strong>Piece size</strong></td>
            <td>{{ object.piece_length|filesizeformat }}</td>
        </tr>
        <tr>
            <td><strong>Privacy</strong></td>
            <td>
                {% if object.private %}
                    <strong class="text-success">Private</strong> — Clients that honour the private flag will not allow you to join multiple
                    swarms at once, and will not allow you to use peer-sharing technologies like DHT.
                {% else %}
                    <strong class="text-danger">Public</strong> — You will not be restricted from joining multiple swarms at once and using
                    peer-sharing technologies like DHT.
                {% endif %}
            </td>
        </tr>
    </table>

    <h3>Files</h3>
    <table class="table table-condensed">
        <thead>
            <th>Path</th>
            <th>Size</th>
        </thead>
        <tbody>
            {% for file in object.file_set.all %}
                <tr>
                    <td>
                        <span class="text-muted">{{ file.owning_directory }}</span>/{{ file.filename }}
                    </td>
                    <td>
                        {{ file.length|filesizeformat }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
{% endblock %}

register/templates/register/torrent_list.html
{% extends 'base.html' %}

{% block heading %}
    List of registered torrents
{% endblock %}

{% block content %}
    <table class="table table-condensed">
        <thead>
            <th>Name</th>
        </thead>
        <tbody>
            {% for torrent in object_list %}
                <tr>
                    <td><a href="{{ torrent.get_absolute_url }}">{{ torrent.name }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/base.html
<!DOCTYPE html>

<html lang='en'>
<head>
    <title>Beehive</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="container">
        <h1>beehive</h1>
        <hr />

        <h2>{% block heading %}heading goes here{% endblock %}</h2>

        {% block content %}
            <!-- put content here -->
        {% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>